FROM golang:1.19-alpine AS builder
RUN mkdir /build/
COPY . /build/
WORKDIR /build/
RUN go mod download
RUN CGO_ENABLED=0 GOOS=linux go build -ldflags="-s -w" -a -o app cmd/main/main.go

FROM alpine:latest
COPY --from=builder /build/app .
EXPOSE 8000
ENTRYPOINT [ "./app" ]

